-- Migration 012: TSIG key management (RFC 8945, Technitium parity).
-- Secrets are stored base64-encoded as generated by transfer.CreateTSIGKey.

-- +goose Up
CREATE TABLE IF NOT EXISTS dns_tsig_keys (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    algorithm TEXT NOT NULL DEFAULT 'hmac-sha256',
    secret TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- +goose Down
DROP TABLE IF EXISTS dns_tsig_keys;
