import { test, expect, type Page } from '@playwright/test'
test.setTimeout(30000)

const modal = (page: Page) => page.locator('.n-modal:visible')
const row = (page: Page, text: string) => page.locator('tbody tr').filter({ hasText: text })
async function select(page: Page, label: string, option: string) {
  await modal(page).locator('.n-form-item').filter({ has: page.locator('.n-form-item-label', { hasText: new RegExp(`^${label}[\\s*]*$`) }) }).locator('.n-base-selection').click()
  await page.locator('.n-base-select-option').filter({ hasText: option }).first().click()
}
async function fill(page: Page, label: string, value: string) {
  await modal(page).locator('.n-form-item').filter({ has: page.locator('.n-form-item-label', { hasText: new RegExp(`^${label}[\\s*]*$`) }) }).locator('input, textarea').first().fill(value)
}
async function save(page: Page) {
  const saved = page.waitForResponse(res => res.url().includes('/api/v1/') && ['POST', 'PUT'].includes(res.request().method()))
  await modal(page).getByRole('button', { name: 'Save', exact: true }).click()
  const response = await saved
  expect(response.ok(), await response.text()).toBe(true)
  await expect(modal(page)).toHaveCount(0)
}
async function remove(page: Page, name: string) {
  await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
  await expect(modal(page)).toHaveCount(0)
}

const errors = new WeakMap<Page, string[]>()
test.beforeEach(async ({ page }) => {
  const current: string[] = []
  errors.set(page, current)
  page.on('pageerror', error => current.push(error.message))
  page.on('response', response => { if (response.status() >= 500) current.push(`${response.status()} ${response.url()}`) })
  await page.addInitScript(() => { if (!localStorage.getItem('locale')) localStorage.setItem('locale', 'en-US') })
  await page.goto('/login')
  await page.getByRole('textbox').nth(0).fill(process.env.GODDI_TEST_USERNAME || 'admin')
  await page.getByRole('textbox').nth(1).fill(process.env.GODDI_TEST_PASSWORD || 'Admin@123456')
  await page.getByRole('button', { name: 'Login', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
})
test.afterEach(async ({ page }) => { expect(errors.get(page)).toEqual([]) })

for (const [path, create] of [['/ipam/spaces', 'Create Space'], ['/admin/groups', 'Create Group'], ['/admin/roles', 'Create Role']]) {
  test(`${create}: create, edit, dismiss confirmation, reopen, delete`, async ({ page }) => {
    const name = `ui-${Date.now()}`
    await page.goto(path!)
    await page.getByRole('button', { name: create!, exact: true }).click()
    await fill(page, 'Name', name)
    await fill(page, 'Description', 'Created through the user interface')
    await save(page)
    await expect(row(page, name)).toBeVisible()
    await row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
    await fill(page, 'Description', 'Updated through the user interface')
    await save(page)
    await expect(row(page, name)).toContainText('Updated through')
    await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
    await expect(modal(page)).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(modal(page)).toHaveCount(0)
    await remove(page, name)
  })
}

test('DNS zone and record lifecycle with search and export', async ({ page }) => {
  const name = `ui-${Date.now()}.example`
  await page.goto('/dns/zones')
  await page.getByRole('button', { name: 'Create Zone', exact: true }).click()
  await fill(page, 'Zone Name', name)
  await save(page)
  await row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByRole('button', { name: 'Create Record', exact: true }).click()
  await fill(page, 'Record Name', 'www')
  await fill(page, 'Record Value', '192.0.2.42')
  await save(page)
  await expect(row(page, '192.0.2.42')).toBeVisible()
  await row(page, '192.0.2.42').getByRole('button', { name: 'Edit', exact: true }).click()
  await modal(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Create Record', exact: true }).click()
  await expect(modal(page).locator('.n-form-item').filter({ hasText: 'Record Name' }).locator('input')).toHaveValue('')
  await modal(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  await row(page, '192.0.2.42').getByRole('button', { name: 'Edit', exact: true }).click()
  await fill(page, 'Record Value', '192.0.2.43')
  await save(page)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Zone', exact: true }).click()
  expect((await download).suggestedFilename()).toBeTruthy()
  await remove(page, '192.0.2.43')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByPlaceholder('Search', { exact: true }).fill(name)
  await page.getByPlaceholder('Search', { exact: true }).press('Enter')
  await expect(row(page, name)).toBeVisible()
  await remove(page, name)
  await page.getByRole('button', { name: 'Language', exact: true }).click()
  await page.getByText('简体中文', { exact: true }).click()
  await expect(page.getByRole('columnheader', { name: '区域名称', exact: true })).toBeVisible()
})

test('forwarder lifecycle and enabled switch persistence', async ({ page }) => {
  const name = `ui-${Date.now()}`
  await page.goto('/dns/forwarders')
  await page.getByRole('button', { name: 'Create Forwarder', exact: true }).click()
  await fill(page, 'Name', name)
  await fill(page, 'Address', '192.0.2.53:53')
  await save(page)
  await row(page, name).getByRole('switch').click()
  await expect(row(page, name).getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await page.reload()
  await expect(row(page, name).getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
})

test('DHCP scope lifecycle and validation', async ({ page }) => {
  const name = `ui-${Date.now()}`
  await page.goto('/dhcp/scopes')
  await page.getByRole('button', { name: 'Create Scope', exact: true }).click()
  await fill(page, 'Name', name)
  await fill(page, 'Subnet', '192.0.2.0/24')
  await fill(page, 'Start IP', '192.0.2.20')
  await fill(page, 'End IP', '192.0.2.80')
  await save(page)
  await expect(row(page, name)).toContainText('192.0.2.20')
  await row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
  await fill(page, 'End IP', '192.0.2.90')
  await save(page)
  await expect(row(page, name)).toContainText('192.0.2.90')
  await remove(page, name)
})

test('backup create, download, restore confirmation and delete', async ({ page }) => {
  await page.goto('/settings/backup')
  await page.getByRole('button', { name: 'Create Backup', exact: true }).click()
  const first = page.locator('tbody tr').first()
  await expect(first).toContainText('completed')
  const download = page.waitForEvent('download')
  await first.getByRole('button', { name: 'Download', exact: true }).click()
  expect((await download).suggestedFilename()).toBeTruthy()
  await first.getByRole('button', { name: 'Restore Backup', exact: true }).click()
  const restored = page.waitForResponse(response => response.url().endsWith('/restore') && response.request().method() === 'POST')
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  expect((await restored).status()).toBe(200)
  await expect(modal(page)).toHaveCount(0)
  await first.getByRole('button', { name: 'Delete', exact: true }).click()
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(modal(page)).toHaveCount(0)
})

test('appearance persistence, all pages at mobile width, and navigation', async ({ page }) => {
  await page.getByRole('switch', { name: 'Dark appearance' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('switch', { name: 'Dark appearance' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.locator('.n-drawer').getByText('DNS Management', { exact: true }).click()
  await page.locator('.n-drawer').getByText('Zones', { exact: true }).click()
  await expect(page).toHaveURL(/dns\/zones/)
  await page.getByRole('button', { name: 'Create Zone', exact: true }).click()
  const bounds = await modal(page).boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(358)
  await modal(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  for (const path of ['/dns/zones','/dns/forwarders','/dns/security','/dns/cache','/dns/client','/dhcp/scopes','/dhcp/leases','/dhcp/reservations','/dhcp/options','/ipam/spaces','/ipam/subnets','/ipam/addresses','/admin/users','/admin/roles','/admin/groups','/admin/tokens','/logs/audit','/logs/dns','/logs/dhcp','/settings','/settings/backup']) {
    await page.goto(path)
    await expect(page.getByRole('heading', { level: 2 }).first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), path).toBe(true)
  }
})

test('IPAM subnet creation, allocation, release and available filter', async ({ page }) => {
  const name = `ui-ipam-${Date.now()}`
  await page.goto('/ipam/spaces')
  await page.getByRole('button', { name: 'Create Space', exact: true }).click()
  await fill(page, 'Name', name)
  await save(page)
  await page.goto('/ipam/subnets')
  await page.getByRole('button', { name: 'Create Subnet', exact: true }).click()
  await fill(page, 'Name', name)
  await select(page, 'Address Spaces', name)
  await fill(page, 'CIDR', '198.51.100.0/28')
  await save(page)
  await expect(row(page, name)).toBeVisible()
  await page.goto('/ipam/addresses')
  await page.getByRole('button', { name: 'Allocate IP', exact: true }).click()
  await select(page, 'Subnets', name)
  await fill(page, 'IP Address', '198.51.100.2')
  await fill(page, 'Hostname', 'ui-client')
  await save(page)
  await row(page, '198.51.100.2').getByRole('button', { name: 'Release IP' }).click()
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(row(page, '198.51.100.2')).toContainText('available')
  await page.locator('.n-base-selection').filter({ hasText: 'Status' }).click()
  await page.locator('.n-base-select-option').filter({ hasText: 'Free' }).click()
  await expect(row(page, '198.51.100.2')).toBeVisible()
  await page.goto('/ipam/subnets')
  await remove(page, name)
  await page.goto('/ipam/spaces')
  await remove(page, name)
})

test('user lifecycle and token creation, copy and revocation', async ({ page, context }) => {
  const name = `ui_user_${Date.now()}`
  await page.goto('/admin/users')
  await page.getByRole('button', { name: 'Create User', exact: true }).click()
  await fill(page, 'Username', name)
  await fill(page, 'Password', 'OnlyForUi-Test-123!')
  await fill(page, 'Email', `${name}@example.com`)
  await fill(page, 'Display Name', name)
  await save(page)
  await expect(row(page, name)).toBeVisible()
  await row(page, name).getByRole('switch').click()
  await expect(row(page, name).getByRole('switch')).not.toBeChecked()
  await page.reload()
  await expect(row(page, name).getByRole('switch')).not.toBeChecked()
  await row(page, name).getByRole('switch').click()
  await expect(row(page, name).getByRole('switch')).toBeChecked()
  await remove(page, name)
  await page.goto('/admin/tokens')
  await page.getByRole('button', { name: 'Create Token', exact: true }).click()
  await fill(page, 'Token Name', name)
  await modal(page).getByRole('button', { name: 'Save', exact: true }).click()
  await expect(modal(page).locator('textarea')).toHaveValue(/^.{32,}$/)
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await modal(page).getByRole('button', { name: 'Copy Token', exact: true }).click()
  expect((await page.evaluate(() => navigator.clipboard.readText())).length).toBeGreaterThan(32)
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  await remove(page, name)
})

test('security lists and policies through all tabs', async ({ page }) => {
  const name = `ui-policy-${Date.now()}`
  await page.goto('/dns/security')
  await page.getByRole('button', { name: 'Create Block List', exact: true }).click()
  await fill(page, 'Name', name)
  await save(page)
  await expect(row(page, name)).toBeVisible()
  await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
  await page.locator('.n-tabs-tab').filter({ hasText: 'Allow Rules' }).click()
  await page.getByRole('button', { name: 'Add Allow Rule', exact: true }).click()
  await fill(page, 'Pattern', `${name}.example`)
  await save(page)
  await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
  await page.locator('.n-tabs-tab').filter({ hasText: 'Client Policies' }).click()
  await page.getByRole('button', { name: 'Create Policy', exact: true }).click()
  await fill(page, 'Name', name)
  await fill(page, 'Source CIDR', '192.0.2.0/24')
  await save(page)
  await row(page, name).getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
})

test('DHCP option lifecycle, cache flush and unchanged setting save', async ({ page }) => {
  const name = `ui-options-${Date.now()}`
  await page.goto('/dhcp/scopes')
  await page.getByRole('button', { name: 'Create Scope', exact: true }).click()
  await fill(page, 'Name', name)
  await fill(page, 'Subnet', '203.0.113.0/24')
  await fill(page, 'Start IP', '203.0.113.20')
  await fill(page, 'End IP', '203.0.113.80')
  await save(page)
  await page.goto('/dhcp/options')
  await page.getByRole('button', { name: 'Create Option', exact: true }).click()
  await fill(page, 'Option Code', '15')
  await fill(page, 'Option Value', 'ui-test.example')
  await select(page, 'Scope', name)
  await save(page)
  await remove(page, 'ui-test.example')
  await page.goto('/dhcp/reservations')
  await page.getByRole('button', { name: 'Create Reservation', exact: true }).click()
  await fill(page, 'IP Address', '203.0.113.30')
  await fill(page, 'MAC Address', '02:00:00:00:00:30')
  await fill(page, 'Hostname', 'ui-reservation')
  await select(page, 'Scope', name)
  await save(page)
  await remove(page, '203.0.113.30')
  await page.goto('/dhcp/scopes')
  await remove(page, name)
  await page.goto('/dns/cache')
  await page.getByRole('button', { name: 'Flush Cache', exact: true }).click()
  await modal(page).getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(modal(page)).toHaveCount(0)
  await page.goto('/settings')
  const button = page.getByRole('button', { name: 'Save', exact: true }).first()
  if (await button.count()) {
    const response = page.waitForResponse(res => res.url().includes('/settings/') && res.request().method() === 'PUT')
    await button.click()
    expect((await response).status()).toBe(200)
  }
})

test('server pagination shows the next page instead of slicing it twice', async ({ page }) => {
  test.setTimeout(60000)
  const prefix = `ui-pages-${Date.now()}`
  await page.goto('/ipam/spaces')
  const headers = await page.evaluate(() => ({ Authorization: `Bearer ${sessionStorage.getItem('token')}`, 'X-CSRF-Token': sessionStorage.getItem('csrf_token') || '' }))
  try {
    for (let i = 0; i < 11; i++) {
      await page.getByRole('button', { name: 'Create Space', exact: true }).click()
      await fill(page, 'Name', `${prefix}-${i}`)
      await save(page)
    }
    await page.locator('.n-pagination .n-base-selection').click()
    await page.locator('.n-base-select-option').filter({ hasText: /^10/ }).click()
    await expect(page.locator('tbody tr')).toHaveCount(10)
    await page.locator('.n-pagination-item').filter({ hasText: /^2$/ }).click()
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await expect(page.locator('tbody tr')).toContainText(prefix)
  } finally {
    const response = await page.request.get('/api/v1/ipam/spaces?page_size=100', { headers })
    for (const space of (await response.json()).data) {
      if (space.name.startsWith(prefix)) await page.request.delete(`/api/v1/ipam/spaces/${space.id}`, { headers })
    }
  }
})

test('desktop, dark, mobile and login visual states', async ({ page }) => {
  await page.setViewportSize({ width: 1536, height: 1024 })
  await page.getByRole('button', { name: 'Language', exact: true }).click()
  await page.getByText('简体中文', { exact: true }).click()
  await expect(page.getByRole('heading', { name: '仪表盘', exact: true })).toBeVisible()
  const capture = async (name: string) => {
    await expect(page.locator('.n-message')).toHaveCount(0)
    if (process.env.GODDI_VISUAL_DIR) await page.screenshot({ path: `${process.env.GODDI_VISUAL_DIR}/${name}.png`, fullPage: true, animations: 'disabled' })
  }
  await capture('desktop')
  await page.getByRole('switch', { name: '深色外观' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await capture('dark')
  await page.getByRole('switch', { name: '深色外观' }).click()
  await page.goto('/dns/zones')
  await capture('zones')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '新建区域', exact: true }).click()
  await expect(modal(page)).toBeVisible()
  const mobileLabel = modal(page).locator('.n-form-item-label').first()
  await expect(mobileLabel).toHaveCSS('display', 'flex')
  await expect(mobileLabel).toHaveCSS('text-align', 'left')
  await capture('mobile-form')
  await modal(page).getByRole('button', { name: '取消', exact: true }).click()
  await page.goto('/settings')
  await capture('mobile-settings')
  await page.setViewportSize({ width: 1536, height: 1024 })
  await page.getByRole('button', { name: 'Administrator', exact: true }).click()
  await page.getByText('退出登录', { exact: true }).click()
  await expect(page).toHaveURL(/login/)
  await capture('login')
})
