/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin_groups: () => import("@/views/admin/groups/index.vue"),
  admin_roles: () => import("@/views/admin/roles/index.vue"),
  admin_sessions: () => import("@/views/admin/sessions/index.vue"),
  admin_tokens: () => import("@/views/admin/tokens/index.vue"),
  admin_users: () => import("@/views/admin/users/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  dhcp_leases: () => import("@/views/dhcp/leases/index.vue"),
  dhcp_options: () => import("@/views/dhcp/options/index.vue"),
  dhcp_reservations: () => import("@/views/dhcp/reservations/index.vue"),
  dhcp_scopes: () => import("@/views/dhcp/scopes/index.vue"),
  dns_cache: () => import("@/views/dns/cache/index.vue"),
  dns_forwarders: () => import("@/views/dns/forwarders/index.vue"),
  dns_security: () => import("@/views/dns/security/index.vue"),
  "dns_zone-detail": () => import("@/views/dns/zone-detail/[id].vue"),
  dns_zones: () => import("@/views/dns/zones/index.vue"),
  ipam_addresses: () => import("@/views/ipam/addresses/index.vue"),
  ipam_spaces: () => import("@/views/ipam/spaces/index.vue"),
  ipam_subnets: () => import("@/views/ipam/subnets/index.vue"),
  logs_audit: () => import("@/views/logs/audit/index.vue"),
  logs_dhcp: () => import("@/views/logs/dhcp/index.vue"),
  logs_dns: () => import("@/views/logs/dns/index.vue"),
  settings_backup: () => import("@/views/settings/backup/index.vue"),
  settings_system: () => import("@/views/settings/system/index.vue"),
  tools_client: () => import("@/views/tools/client/index.vue"),
};
