/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:shield-account',
      order: 6
    },
    children: [
      {
        name: 'admin_groups',
        path: '/admin/groups',
        component: 'view.admin_groups',
        meta: {
          title: 'admin_groups',
          i18nKey: 'route.admin_groups',
          icon: 'mdi:account-group',
          order: 3,
          permission: {
            resource: 'group',
            action: 'read'
          }
        }
      },
      {
        name: 'admin_roles',
        path: '/admin/roles',
        component: 'view.admin_roles',
        meta: {
          title: 'admin_roles',
          i18nKey: 'route.admin_roles',
          icon: 'mdi:account-key',
          order: 2,
          permission: {
            resource: 'role',
            action: 'read'
          }
        }
      },
      {
        name: 'admin_sessions',
        path: '/admin/sessions',
        component: 'view.admin_sessions',
        meta: {
          title: 'admin_sessions',
          i18nKey: 'route.admin_sessions',
          icon: 'mdi:monitor-lock',
          order: 5,
          permission: {
            resource: 'user',
            action: 'read'
          }
        }
      },
      {
        name: 'admin_tokens',
        path: '/admin/tokens',
        component: 'view.admin_tokens',
        meta: {
          title: 'admin_tokens',
          i18nKey: 'route.admin_tokens',
          icon: 'mdi:key-variant',
          order: 4,
          permission: {
            resource: 'token',
            action: 'read'
          }
        }
      },
      {
        name: 'admin_users',
        path: '/admin/users',
        component: 'view.admin_users',
        meta: {
          title: 'admin_users',
          i18nKey: 'route.admin_users',
          icon: 'mdi:account-multiple',
          order: 1,
          permission: {
            resource: 'user',
            action: 'read'
          }
        }
      }
    ]
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'dhcp',
    path: '/dhcp',
    component: 'layout.base',
    meta: {
      title: 'dhcp',
      i18nKey: 'route.dhcp',
      icon: 'mdi:lan',
      order: 4
    },
    children: [
      {
        name: 'dhcp_leases',
        path: '/dhcp/leases',
        component: 'view.dhcp_leases',
        meta: {
          title: 'dhcp_leases',
          i18nKey: 'route.dhcp_leases',
          icon: 'mdi:license',
          order: 2,
          permission: {
            resource: 'dhcp',
            action: 'read'
          }
        }
      },
      {
        name: 'dhcp_options',
        path: '/dhcp/options',
        component: 'view.dhcp_options',
        meta: {
          title: 'dhcp_options',
          i18nKey: 'route.dhcp_options',
          icon: 'mdi:tune',
          order: 4,
          permission: {
            resource: 'dhcp',
            action: 'read'
          }
        }
      },
      {
        name: 'dhcp_reservations',
        path: '/dhcp/reservations',
        component: 'view.dhcp_reservations',
        meta: {
          title: 'dhcp_reservations',
          i18nKey: 'route.dhcp_reservations',
          icon: 'mdi:bookmark',
          order: 3,
          permission: {
            resource: 'dhcp',
            action: 'read'
          }
        }
      },
      {
        name: 'dhcp_scopes',
        path: '/dhcp/scopes',
        component: 'view.dhcp_scopes',
        meta: {
          title: 'dhcp_scopes',
          i18nKey: 'route.dhcp_scopes',
          icon: 'mdi:map',
          order: 1,
          permission: {
            resource: 'dhcp',
            action: 'read'
          }
        }
      }
    ]
  },
  {
    name: 'dns',
    path: '/dns',
    component: 'layout.base',
    meta: {
      title: 'dns',
      i18nKey: 'route.dns',
      icon: 'mdi:dns',
      order: 2
    },
    children: [
      {
        name: 'dns_allowed',
        path: '/dns/allowed',
        component: 'view.dns_allowed',
        meta: {
          title: 'dns_allowed',
          i18nKey: 'route.dns_allowed',
          icon: 'mdi:shield-check-outline',
          order: 3,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_apps',
        path: '/dns/apps',
        component: 'view.dns_apps',
        meta: {
          title: 'dns_apps',
          i18nKey: 'route.dns_apps',
          icon: 'mdi:apps',
          order: 7,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_blocked',
        path: '/dns/blocked',
        component: 'view.dns_blocked',
        meta: {
          title: 'dns_blocked',
          i18nKey: 'route.dns_blocked',
          icon: 'mdi:shield-lock',
          order: 4,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_cache',
        path: '/dns/cache',
        component: 'view.dns_cache',
        meta: {
          title: 'dns_cache',
          i18nKey: 'route.dns_cache',
          icon: 'mdi:database-clock',
          order: 6,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_forwarders',
        path: '/dns/forwarders',
        component: 'view.dns_forwarders',
        meta: {
          title: 'dns_forwarders',
          i18nKey: 'route.dns_forwarders',
          icon: 'mdi:swap-horizontal',
          order: 2,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_security',
        path: '/dns/security',
        component: 'view.dns_security',
        meta: {
          title: 'dns_security',
          i18nKey: 'route.dns_security',
          icon: 'mdi:shield-check',
          order: 5,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      },
      {
        name: 'dns_zone-detail',
        path: '/dns/zone-detail/:id',
        component: 'view.dns_zone-detail',
        meta: {
          title: 'dns_zone-detail',
          i18nKey: 'route.dns_zone-detail',
          permission: {
            resource: 'dns',
            action: 'read'
          },
          hideInMenu: true
        }
      },
      {
        name: 'dns_zones',
        path: '/dns/zones',
        component: 'view.dns_zones',
        meta: {
          title: 'dns_zones',
          i18nKey: 'route.dns_zones',
          icon: 'mdi:dns',
          order: 1,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      }
    ]
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'ipam',
    path: '/ipam',
    component: 'layout.base',
    meta: {
      title: 'ipam',
      i18nKey: 'route.ipam',
      icon: 'mdi:ip-network',
      order: 5
    },
    children: [
      {
        name: 'ipam_addresses',
        path: '/ipam/addresses',
        component: 'view.ipam_addresses',
        meta: {
          title: 'ipam_addresses',
          i18nKey: 'route.ipam_addresses',
          icon: 'mdi:ip',
          order: 3,
          permission: {
            resource: 'ipam',
            action: 'read'
          }
        }
      },
      {
        name: 'ipam_spaces',
        path: '/ipam/spaces',
        component: 'view.ipam_spaces',
        meta: {
          title: 'ipam_spaces',
          i18nKey: 'route.ipam_spaces',
          icon: 'mdi:earth',
          order: 1,
          permission: {
            resource: 'ipam',
            action: 'read'
          }
        }
      },
      {
        name: 'ipam_subnets',
        path: '/ipam/subnets',
        component: 'view.ipam_subnets',
        meta: {
          title: 'ipam_subnets',
          i18nKey: 'route.ipam_subnets',
          icon: 'mdi:subnet',
          order: 2,
          permission: {
            resource: 'ipam',
            action: 'read'
          }
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'logs',
    path: '/logs',
    component: 'layout.base',
    meta: {
      title: 'logs',
      i18nKey: 'route.logs',
      icon: 'mdi:file-document-multiple',
      order: 7
    },
    children: [
      {
        name: 'logs_audit',
        path: '/logs/audit',
        component: 'view.logs_audit',
        meta: {
          title: 'logs_audit',
          i18nKey: 'route.logs_audit',
          icon: 'mdi:clipboard-text-search',
          order: 1,
          permission: {
            resource: 'audit',
            action: 'read'
          }
        }
      },
      {
        name: 'logs_dhcp',
        path: '/logs/dhcp',
        component: 'view.logs_dhcp',
        meta: {
          title: 'logs_dhcp',
          i18nKey: 'route.logs_dhcp',
          icon: 'mdi:lan-connect',
          order: 3,
          permission: {
            resource: 'dhcp',
            action: 'read'
          }
        }
      },
      {
        name: 'logs_dns',
        path: '/logs/dns',
        component: 'view.logs_dns',
        meta: {
          title: 'logs_dns',
          i18nKey: 'route.logs_dns',
          icon: 'mdi:dns-search',
          order: 2,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog',
      order: 8,
      permission: {
        resource: 'settings',
        action: 'read'
      }
    },
    children: [
      {
        name: 'settings_backup',
        path: '/settings/backup',
        component: 'view.settings_backup',
        meta: {
          title: 'settings_backup',
          i18nKey: 'route.settings_backup',
          icon: 'mdi:backup-restore',
          order: 1,
          permission: {
            resource: 'backup',
            action: 'read'
          }
        }
      },
      {
        name: 'settings_config-versions',
        path: '/settings/config-versions',
        component: 'view.settings_config-versions',
        meta: {
          title: 'settings_config-versions',
          i18nKey: 'route.settings_config-versions',
          icon: 'mdi:source-branch',
          order: 2,
          permission: {
            resource: 'settings',
            action: 'read'
          }
        }
      },
      {
        name: 'settings_system',
        path: '/settings/system',
        component: 'view.settings_system',
        meta: {
          title: 'settings_system',
          i18nKey: 'route.settings_system'
        }
      }
    ]
  },
  {
    name: 'tools',
    path: '/tools',
    component: 'layout.base',
    meta: {
      title: 'tools',
      i18nKey: 'route.tools',
      icon: 'mdi:wrench',
      order: 3
    },
    children: [
      {
        name: 'tools_client',
        path: '/tools/client',
        component: 'view.tools_client',
        meta: {
          title: 'tools_client',
          i18nKey: 'route.tools_client',
          icon: 'mdi:console-network',
          order: 1,
          permission: {
            resource: 'dns',
            action: 'read'
          }
        }
      }
    ]
  }
];
